project:
  type: book
  output-dir: _book

crossref:
  fig-title: Fig.
  fig-prefix: Fig.
  sec-prefix: Ponto
  tbl-prefix: Tabela
  tbl-title: Tabela

book:
  title: "Introdução à Análise de Dados em Arqueologia"

  page-footer:
    left: |
      Introdução à Análise de Dados em Arqueologia foi escrito por João Cascalheira.
    right: |
      Este livro foi construido com <a href="https://quarto.org/">Quarto</a>.
  cover-image: cover.png
  favicon: cover.png
  repo-url: https://github.com/jmcascalheira/IADA
  repo-branch: main
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    
    - preambulo.qmd
    - introducao.qmd
    
    - part: "Dados e Bases de Dados"
      chapters:
        - basesdados.qmd
        - tiposdedados.qmd
        
    - part: "Recolha de dados"
      chapters:
        - recolha.qmd
        - E5.qmd
    
    - part: "Transformação de dados"
      chapters:
        - formatar.qmd
        - operadores.qmd
    
    - part: "Estatística descritiva univariada"
      chapters:
        - tiposvariaveis.qmd
        - qualitativas.qmd
        - quantitativas.qmd

    - part: "Estatística descritiva bivariada"
      chapters:
        - duascategoricas.qmd
        - umacatumanum.qmd
        - duasnumericas.qmd

    - referencias.qmd
    - anexos.qmd

bibliography: biblio.bib

format:
  html:
    theme: 
      - cosmo
      - 4rds.scss
    code-link: true
    
    author-meta: "João Cascalheira"
    callout-appearence: simple

editor: visual
