# Apresentação {#sec-apresentacao}

O termo "dados" (*data* em inglês) é hoje usado em muitos e diferentes contextos e é quase sinónimo da utilização de computadores @lock. Veja-se, por exemplo, como o campo interdisciplinar denominado de "Ciência dos Dados" foi pela primeira vez proposto em 1974 por Peter Naur como nome alternativo para a chamada Ciência de Computação. No entanto a definição do que são "dados" é um problema de investigação por si próprio para os cientistas da informação [@leonelli2016; @borgman2012].

É comum assumir-se que os arqueólogos recolhem dados e os introduzem e, computadores. Consequentemente, afirmar que tanto a arqueologia como os computadores dependem de dados parece óbvio e carece de profundidade. Para obter uma compreensão mais profunda, temos de explorar o conceito de dados arqueológicos, a sua potencial relação com dados compatíveis com computadores e as suas implicações no registo arqueológico, na cultura material, na teoria, na interpretação, nas metodologias, na análise e no significado. Além disso, devemos examinar a forma como as ideias relacionadas com a computação, como "tecnologia", "objetividade" e "científico", se entrelaçam com a arqueologia, particularmente no âmbito da subdisciplina de arqueoinformática.

Em termos gerais, a Arqueologia pré-década de 1960 estava maioritariamente baseada numa descrição empírica da cultural material, o que incluía acreditar que uma grande quantidade de dados falariam sempre por eles próprios. Os padrões emergiriam do estudo descritivo de coleções de dados para que as cerâmicas, ferramentas em pedra ou estruturas arqueológicas fizessem sentido agrupadas de acordo com determinadas características, a que depois eram atribuídos limites espaciais e temporais através do conceito Childeano de Cultura. Devido a este contexto teórico, os dados eram tidos como adquiridos pela maior parte dos arqueólogos e o processo de observação, registo e interpretação precisava de pouca, se não mesmo nenhuma, justificação.

As mudanças com a Nova Arqueologia, a partir dos finais dos anos 1960, mas com maior intensidade a partir da década de 1970, anunciaram a introdução do Método Científico e a rejeição da percepção subjetiva do empirismo arqueológico. No centro desta nova corrente estava o acreditar na objetividade através da observação sistemática, medindo e registando dados através da adopção dos denominados métodos quantitativos. A objetividade era possível separando a teoria da prática para os que os dados existissem e pudessem ser medidos de forma independente por um qualquer sujeito observador. Assim, enquanto a ligação anterior entre dados e teoria era indutiva, i.e. uma recolha imparcial de "todos" os dados iria produzir teoria, o novo paradigma da arqueologia processual tinha como ponto central um raciocínio hipotético-dedutivo em que o conhecimento é acumulado através do teste de hipóteses explicitas (muitos vezes através do uso de testes estatísticos de significância) sobre dados recolhidos na base do que seria relevante para a análise [@trigger1998]. A grande implicação do método científico para a Arqueologia tornou-se assim na possibilidade de criar uma arqueologia global, unida por métodos estandardizados de análise que pudessem ser aplicados a qualquer conjunto de dados para estabelecer generalizações interculturais ou até mesmo "leis" do conhecimento arqueológico. Se avançarmos para os dias de hoje, estas alterações serviram como pedra basilar para algumas das mais recentes revoluções na forma como se pensa e se pratica a Arqueologia. Fenómenos como a chamada "crise da replicação" e as alterações que esta acarretou na maneira de como recolhemos, gerimos e partilhamos os dados arqueológicos, estão a transformar a Arqueologia.

Como noutras disciplinas, quando vários estudos arqueológicos independentes demonstram resultados semelhantes, consideramos que esses resultados são uma aproximação razoável ao comportamento humano do passado. Esta capacidade de reproduzir os resultados de outros estudos é um princípio fundamental do método científico e, quando as reproduções são bem sucessidas, a disciplina avança. Em Arqueologia, existe uma longa tradição de testes empíricos de reproducibilidade quando, por exemplo, se retorna a sítios escavados por gerações anteriores de arqueólogos ou quando se reexaminam coleções de museus com novos métodos. Contudo, pouco progresso foi feito no que diz respeito a testar a replicabilidade dos dados recolhidos e das respetivas análises quantitativas. Este problema advém de duas razões principais. Primeiro, a maior parte das publicações raramente contém informações suficientes para outro arqueólogo reproduzir os resultados [@marwick2016]. Segundo, a formação base dos arqueólogos raramente inclui o desenvolvimento de competências de organização, gestão e análise de dados. Esta falta de integração de uma componente de literacia dos dados (do inglês *data literacy*, definida como a capacidade de ler, trabalhar, analisar e comunicar com dados) na formação em Arqueologia, prejudica a qualidade dos dados arqueológicos, inibe a sua reutilização, e limita a capacidade que os arqueólogos muitas vezes têm em comunicar num contexto interdisciplinar e consequentemente, a contribuição que podemos ter em conversas contemporâneas fora do âmbito da Arqueologia (apesar de estarmos supostamente bem posicionados para o fazer, ver [@kintigh2014]).

Neste contexto, a literacia dos dados não se trata principalmente de permitir que os indivíduos dominem uma habilidade específica ou se tornem proficientes numa determinada plataforma de tecnologia. Em vez disso, trata-se de equipar os arqueólogos com ferramentas para entender os princípios subjacentes e os desafios dos dados [@bhargava2015; @kansa2021]. Atualmente não faltam discussões e iniciativas sobre as promessas e os perigos de alavancar dados em vários tamanhos e formas para enfrentar os desafios do mundo como parte da *Data Revolution*, invocada em 2015 pelas Nações Unidas sobre a agenda de desenvolvimento global. Um artigo, amplamente citado, publicado pelo jornal *The Economist* intitulado "The Data Deluge: Businesses, Governments and Society Are Only Starting to Tap Its Vast Potential" [@cukier2010] teve como um dos primeiros comentários online o seguinte: "Aqui estão os empregos do século XXI (\...). Por favor entendam e eduquem a próxima geração em conformidade".

A importância da literacia dos dados (bem como a demonimada literacia digital) para um aluno que termina qualquer curso superior nos dias que correm não deve ser desvalorizada. Em Arqueologia, especificamente, é urgente a mudança para perfis profissionais em que a especialização e a profundidade de conhecimentos se conjuguem com uma maior amplitude de conhecimento no uso e tratamento de dados por meios digitais (ver @fig-pishaped). A crescente importância dos métodos digitais de registo, gestão e comunicação dos achados arqueológicos, obrigam necessariamente a que todos os profissionais, tenham um nível básico de literacia dos dados, de preferência através de programas especificamente direcionado para as especificidades dos dados arqueológicos.

![Perfis profissionais em forma de "T" vs forma de "Pi". Adaptado de [@marwick2016].](pishaped.png){#fig-pishaped}
