# A unidade curricular no quadro da licenciatura em Património Cultural e Arqueologia

A Introdução à Análise de Dados em Arqueologia (abreviadamente, IADA) é uma das unidades curriculares optativas do curso de licenciatura em Património Cultural e Arqueologia da Universidade do Algarve, destinando-se, na estrutura do curso, aos alunos que frequentem o 2º e 3º ano.

Esta unidade curricular funcionou pela primeira vez no ano letivo de 2016/2017, repetindo-se em 2017/2018 e 2020/2021. A sua existência resulta de uma necessidade muito concreta: a de preencher uma lacuna na estrutura do curso no que diz respeito ao ensino das técnicas e metodologias computacionais de tratamento, análise e apresentação de dados arqueológicos. Tradicionalmente, no âmbito da licenciatura em Património Cultural e Arqueologia, estes aspectos fundamentais para qualquer profissional de arqueologia, eram lecionados ou no âmbito das disciplinas de técnicas de análise laboratorial (e.g., cerâmicas, líticos, faunas), ou no contexto da realização de trabalhos de seminário de conclusão de curso. Quer num caso, quer noutro, os alunos para além de terem de desenvolver conhecimentos específicos sobre cada uma das disciplinas, bem como desenvolver o trabalho analítico dos materiais em questão, têm ainda que aprender a construir e manter as bases de dados resultantes da análise de conjuntos arqueológicos, escolher as melhores abordagens para as analisar, e finalmente criar e interpretar elementos gráficos com base nos dados recolhidos. Com base na minha experiência anterior na lecionação das disciplinas de análise de materiais líticos, bem como na orientação de alunos de licenciatura e do mestrado em Arqueologia da UAlg, frequentemente ficou patente a dificuldade que os alunos demonstram neste âmbito, fruto das lacunas relacionadas com a literacia dos dados (ver @sec-apresentacao para mais informação), nomeadamente a falta de um conhecimento base sobre os diferentes métodos e procedimentos de recolha, análise e apresentação de dados em Arqueologia.

No panorama nacional, IADA não se trata de uma unidade curricular ímpar, sendo que a maior parte dos planos curriculares de licenciaturas em Arqueologia tem atualmente pelo menos uma disciplina dedicada às técnicas informáticas e métodos digitais aplicados à Arqueologia (@tbl-exemplos). Ainda assim, torna-se evidente, com base na informação disponibilizada nos respectivos *website*, que os conteúdos programáticos de algumas dessas disciplinas têm como foco dominante o uso de Sistemas de Informação Geográfica ou o desenho assistido por computador. Estes tópicos não fazem parte do programa de IADA, sendo tratados em unidades curriculares optativas independentes, como por exemplo a de Sistemas de Informação Geográfica Aplicados à Arqueologia. Por outro lado, é certo que os alunos de grande parte destas licenciaturas, incluindo os da UAlg, têm a opção de frequentar outras unidades curriculares optativas de cursos distintos, dedicadas, por exemplo, à ciência de dados ou à estatítica introdutória. Nem sempre esta é a melhor opção, tendo em conta, principalmente, as particularidades (inclusivamente éticas) dos dados arqueológicos, e as respectivas limitações e oportunidades na aplicação de determinadas abordagens.

| Instituição - Curso                                            | Unidade Curricular                 | Links                                                                                    |
|----------------------------------------------------------------|------------------------------------|------------------------------------------------------------------------------------------|
| Universidade Nova de Lisboa - Licenciatura em Arqueologia      | Métodos digitais em Arqueologia    | https://guia.unl.pt/pt/2022/fcsh/program/9006/course/01105677                            |
| Universidade de Coimbra - Licenciatura em Arqueologia          | Informática Aplicada à Arqueologia | https://apps.uc.pt/courses/PT/unit/80479/22541/2023-2024?type=ram&id=5382                |
| Universidade de Évora - Licenciatura em História e Arqueologia | Introdução às Humanidades Digitais | https://www.uevora.pt/estudar/cursos/licenciaturas?cod=8251&v=plano-estudos&uc=HIS12024L |
| Universidade do Minho - Licenciatura em Arqueologia            | Tratamento Digital da Informação   | https://www.ics.uminho.pt/pt/Ensino/Licenciaturas/Arqueologia                            |

: Exemplos de unidades curriculares disponibilizadas noutras instituições com componentes relacionadas com a análise de dados em Arqueologia. {#tbl-exemplos}

O número de alunos inscritos em IADA, nas três edições do curso em que esta foi leccionada, foi de 4 alunos em 2016/2017, e 7 alunos em 2017/2018 e em 2020/2021. Tratando-se de uma unidade curricular optativa destinada apenas aos alunos que optem pelo ramo de Arqueologia no 2º ano do curso, a consolidação numérica das duas últimas edições transparece uma relativamente boa aceitação dos alunos. Por outro lado, tendo em conta a grande componente prática da unidade curricular, estes números permitiram cumprir os pressupostos do processo de Bolonha com um processo de ensino/aprendizagem mais centrado no aluno.

Do ponto de vista da avaliação, a média geral da avaliação de todos alunos de todas as edições de IADA situa-se em 14.8 valores. Deve salientar-se ainda, a este respeito, que as avaliações individuais registadas acima destas médias se distribuem entre 15 e 19 valores, e abaixo entre os 14 e os 4 valores. Neste último caso, as duas reprovações estão claramente relacionadas com a fraca assiduidade dos alunos, o que revela algum peso para a componente letiva presencial no âmbito desta unidade curricular.

Apesar do sucesso relativamente elevado dos alunos de IADA, são de salientar dois casos específicos, por terem não só cumprido os objetivos da unidade curricular, mas porque puderam, posteriormente, revelar a importância dos conteúdos aprendidos para o sucesso do seu percurso enquanto alunos e investigadores. Os dois casos são os de David Nora e Joana Belmiro, cujos seminários finais de licenciatura, bem como as teses de mestrado defendidas na UAlg, incluem ampla utilização das ferramentas e conceitos de recolha, gestão, análise, e partilha de dados introduzidas e exploradas nas versões anteriores de IADA. No caso da Joana Belmiro, a publicação com revisão por pares que teve origem na sua tese de mestrado [@belmiro2019], utilizou os principios discutidos em IADA sobre a importância da transparência e da partilha dos dados em Arqueologia.
